DECLARING NUMPY ARRAY

NOTE: HAVE COVERED MOST OF THE IMPORTANT USED FUNCTIONS WHICH ARE LITTLE TRICKY

In [ ]:
import numpy as np
a=np.array([5,3,'v',7,5,6])
print(a)
print(a.dtype)

['5' '3' 'v' '7' '5' '6']
<U21


In [ ]:
#Reshaping arrays
b=a.reshape(2,3)
print(b),print(b.shape),print(b.ndim);print(b.itemsize)

[['5' '3' 'v']
 ['7' '5' '6']]
(2, 3)
2
84


In [ ]:
#explicitly giving n dimensional structure
c=np.array([[1,2,3],[3,4,5],[3,4,6]])
c.ndim,c.size,len(c),c.itemsize# size of the int in this case-->8 bytes

(2, 9, 3, 8)

In [ ]:
print(b.base is a)# b shares memory with a so true
print(a.base is None)# a is the parent memory so true
print(c.base is None)# c is the parent memory so true
print(c.base is b)# c does not share memory with b or it did not derive from b so false

True
True
True
False


SLICING TECHNIQUES

In [ ]:
print('second row of c',c[1]);print('second row of c',c[1:2])
print('      ')
print('first row of c',c[:1]);print('first row of c',c[0]);print('first row of c',c[0:1])



second row of c [3 4 5]
second row of c [[3 4 5]]
      
first row of c [[1 2 3]]
first row of c [1 2 3]
first row of c [[1 2 3]]


In [ ]:
# going into an element of ndim 
print('second row of first element c',c[1][0]);print('second row of third c',c[1:2][0][2])
#that is the reason this is 2 d array as it is the minimal num of ways to reach the element in the array space

second row of first element c 3
second row of third c 5


In [ ]:
#multi-indexing
c[[1,2],[0,2]]

array([3, 6])

In [245]:
c[np.ix_([0,1],[2,3])]# this will give combinations to index like (0,2) (0,3) (1,2) (1,3) 

array([[3, 4],
       [5, 6]])

In [ ]:
#reshaping it to 3 dim
d=c.reshape(3,1,3)
d

array([[[1, 2, 3]],

       [[3, 4, 5]],

       [[3, 4, 6]]])

UNDERSTANDING TRANSPOSE

In [ ]:
d.transpose(0,1,2)# all the axes needed in the transpose, so it works on the order given

array([[[1, 2, 3]],

       [[3, 4, 5]],

       [[3, 4, 6]]])

In [ ]:
d.transpose(2,0,1)

array([[[1],
        [3],
        [3]],

       [[2],
        [4],
        [4]],

       [[3],
        [5],
        [6]]])

In [ ]:
d.transpose(0,2,1)

array([[[1],
        [2],
        [3]],

       [[3],
        [4],
        [5]],

       [[3],
        [4],
        [6]]])

In [ ]:
e=d.reshape(1,3,3)
e

array([[[1, 2, 3],
        [3, 4, 5],
        [3, 4, 6]]])

In [ ]:
e[0,1,2]

5

In [ ]:
np.count_nonzero(d)# this will give non zero numbers 

9

In [ ]:
z=np.array([[1,2,3],[4,5,6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.diag(z)#diagonal

array([1, 5])

In [ ]:
np.diag(z,-1)# this tries to give one below the main diagonal

In [ ]:

np.diag(z,1)#this tries to give the diagonal one above the main diagonal 

array([2, 6])

In [ ]:
np.trace(z)#sum of diagonal

6

INITIALISING ARRAYS

In [ ]:
a=np.zeros(8)
b=np.zeros((3,2))#giving shape will work
a,b

(array([0., 0., 0., 0., 0., 0., 0., 0.]), array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

In [ ]:
np.eye(4)# returns a 2d array with all 1's in diagonal and 0's elsewhere

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.ones((2,3)),np.isnan(np.ones((2,3)))# is nan evaluates any item in the array if it is null. This is very important to evaluate data in dataframes

(array([[1., 1., 1.],
        [1., 1., 1.]]), array([[False, False, False],
        [False, False, False]]))

In [ ]:
a=np.array([1,2,3,'u'])
a.nbytes# sum of each element data type size

336

In [ ]:
b=np.array([[1,4,7],[3,4,5]])
np.full_like(b,8)# this changes all the elements to 8

array([[8, 8, 8],
       [8, 8, 8]])

In [ ]:
z=np.arange(8,dtype=int)
z #it gives range of numbers until n-1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Note: reshape will never make save changes to the actual one. It needs to be assigned
z.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
z

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.full([2,3],7)# this gives you provision of adjusting a new shape and put the number given in all the indices.

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.full_like([2,3],7)# this takes [2,3] as an array and modifies it to [7,7]

array([7, 7])

SPECIAL FUNCTIONS

In [ ]:
a=np.full([2,2],7)
np.fill_diagonal(a,9)
a# this fills only diagonal 

array([[9, 7],
       [7, 9]])

In [ ]:
a.flatten()# this becomes a one dimension, this kills higher dimension

array([9, 7, 7, 9])

In [ ]:
b=np.arange(8,dtype=int).reshape(2,4)
b.ravel()# this also kills dimension, it flattens

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
b=np.arange(8,dtype=int).reshape(2,4)
b


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
#if you need only 2 cols and the matrix need to be adjusted accordingly for the above array b
c=b.reshape(-1,2)# i am only guaranteed about the number of cols
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
c==5# this will search where the element exists and returns True

array([[False, False],
       [False, False],
       [False,  True],
       [False, False]])

In [ ]:
x=np.array([[1,4],[9,5]])
x[x==9]# this returns the true value ie, 9

array([9])

In [ ]:
np.where(x==9)

(array([1]), array([0]))

In [ ]:
np.repeat(x,2,axis=0)# axis 0 is row, 2 states that each row needs to be repeated 

array([[1, 4],
       [1, 4],
       [9, 5],
       [9, 5]])

In [ ]:
np.repeat(x,3,axis=1)# axis=1 is column wise and each one repeats 3 times 

array([[1, 1, 1, 4, 4, 4],
       [9, 9, 9, 5, 5, 5]])

In [ ]:
q=np.arange(12,dtype=int).reshape(3,4)
q

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
j=q[np.newaxis]
j

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
j.shape

(1, 3, 4)

In [ ]:
t=q[np.newaxis,:]
t# this produces same result as above

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
k=q[:,np.newaxis]
k# new axis is getting added to where you reach your point, its because you are trying to add new axis at last

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [ ]:
k=q[:,np.newaxis,np.newaxis]
k

array([[[[ 0,  1,  2,  3]]],


       [[[ 4,  5,  6,  7]]],


       [[[ 8,  9, 10, 11]]]])

In [ ]:
a=np.arange(10,dtype=int)
a[:,np.newaxis]# this new axis is added to the last for the one dimensional number, so every number should be reached via extra dimensionality


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
a=np.array([2,3,5])
np.vander(a,3)# observe first columns: 4, 9, 25  second columns= 2,3,5   third column=2^0, 3^0,5^0

array([[ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [ ]:
# you can also use column stack as well
n=3
s=np.column_stack([a**(n-i-1) for i in range(n)])
s

array([[ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [ ]:
np.vander(a,3,increasing=True)# increasing order of your column stack

array([[ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

In [ ]:
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
np.hstack([a,b])#stacks side by side


array([1, 2, 3, 4, 3, 4, 5, 6])

In [ ]:
c=np.array([a]+[b])
c

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [ ]:
c=np.vstack([a,b])
c

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [ ]:
a=np.array([[2,3,4],[4,1,7]])
b=np.array([1,2,4])
np.vstack([a,b])#vstack is not so bothered on dimensionality difference between a and b. hstack cant take different dimensionality

array([[2, 3, 4],
       [4, 1, 7],
       [1, 2, 4]])

In [ ]:
a

array([[2, 3, 4],
       [4, 1, 7]])

In [ ]:
np.any(a==4),np.all(a==3)

(True, False)